// Re-export from atomic design layers
export { Button } from '@/components/ui/Button'
export { Input } from '@/components/ui/Input'
export { Icon } from '@/components/atoms/Icon'
export { Pill } from '@/components/atoms/Pill'
export { ToastProvider, useToast, Toaster } from '@/components/atoms/Toast'
export { FormField } from '@/components/molecules/FormField'
export { ListItem } from '@/components/molecules/ListItem'
export { SearchPill } from '@/components/molecules/SearchPill'
export { SheetSelect } from '@/components/molecules/SheetSelect'
export { LiveCard } from '@/components/organisms/LiveCard'
export { DataList } from '@/components/organisms/DataList'
export { FormCard } from '@/components/organisms/FormCard'

// Keep existing shared components
export { EmptyState } from './EmptyState'
export { PageHeader } from './PageHeader'
export { SearchBar } from './SearchBar'
export { DetailRow, DetailList } from './DetailRow'
export { LoadingState } from './LoadingState'
export { FloatingActionButton } from './FloatingActionButton'
export { StatCard } from './StatCard'
export { MetricCard } from './MetricCard'
export { ChartCard } from './ChartCard'
export { DataTable } from './DataTable'
export { StatusBadge } from './StatusBadge'
export { TrendIndicator } from './TrendIndicator'
export { TimeRangePicker } from './TimeRangePicker'
export { ErrorFallback } from './ErrorFallback'
export { InlineError } from './InlineError'
export { GlassCard } from './GlassCard'
export { AppTopBar } from './AppTopBar'
export type { AppTopBarProps } from './AppTopBar'
export { BarChartWidget, LineChartWidget, DoughnutChartWidget } from './Charts'
export { BookedTripCard } from './BookedTripCard'
export { NotificationList } from './NotificationList'
export type { AppNotification } from './NotificationList'
export { FilterPills } from './FilterPills'
export { UserDetailDialog } from './UserDetailDialog'
export { CreateUserDialog } from './CreateUserDialog'
export { InlineCell } from './InlineCell'
export { LocationSelect } from './LocationSelect'
export { NotificationPanel, useUnreadCount } from './NotificationPanel'
export { StatsGrid, StatCard as StatsGridCard } from './StatsGrid'
export { StatTileCard } from './StatTileCard'
export type { StatTile } from './StatTileCard'
export { SparklineChart } from './SparklineChart'
export { StatusBadgePro } from './StatusBadgePro'
export { MonthNavigator } from './MonthNavigator'
export { SectionHeader } from './SectionHeader'
export { PageContainer } from './PageContainer'
export { BackButton } from './BackButton'
export { InfoRow } from './InfoRow'
export { FilterToolbar } from './FilterToolbar'
export { DataTablePro } from './DataTablePro'

// ─── Dialogs & overlays ──────────────────────────────────────────────────────
export { ImportResultDialog } from './ImportResultDialog'
export { ConfirmDialog } from './ConfirmDialog'
export { ConfirmationCheckbox } from './ConfirmationCheckbox'
export { TripSummaryDialog } from './TripSummaryDialog'
export { SuccessOverlay } from './SuccessOverlay'

// ─── Domain-specific components ──────────────────────────────────────────────
export { ContBadge } from './ContBadge'
export { ContainerScanner } from './ContainerScanner'
export { ContainerTypeGrid } from './ContainerTypeGrid'
export { CreateClientDialog } from './CreateClientDialog'
export { CreateVendorDialog } from './CreateVendorDialog'
export { InlineSelect } from './InlineSelect'
export { ContactsTable } from './ContactsTable'
export { RecentTripSuggestions } from './RecentTripSuggestions'
export { RouteDisplay } from './RouteDisplay'
export { SettingsPageLayout } from './SettingsPageLayout'
export { DeliveredTripCard } from './DeliveredTripCard'
export { PricingClientCards, PricingClientDetail, PricingForm, LineEditor } from './Pricing'
export { TopNavBar } from './TopNavBar'
export type { TopNavItem } from './TopNavBar'
export { StatBreakdownCard } from './StatBreakdownCard'

// ─── Driver components ──────────────────────────────────────────────────────
export { DriverFormDrawer } from './DriverFormDrawer'
export type { DriverFormDrawerProps } from './DriverFormDrawer'

// ─── Delivered trip columns ─────────────────────────────────────────────────
export { getDeliveredTripColumns } from './DeliveredTripColumns'
export type { DeliveredTripColumnsOptions } from './DeliveredTripColumns'

// ─── Location components ────────────────────────────────────────────────────
export { HighlightText } from './HighlightText'
export type { HighlightTextProps } from './HighlightText'
export { LocationListItem } from './LocationListItem'
export type { LocationListItemProps } from './LocationListItem'
export { EditableLocationName } from './EditableLocationName'
export type { EditableLocationNameProps } from './EditableLocationName'
export { LocationDetailPanel } from './LocationDetailPanel'
export type { LocationDetailPanelProps } from './LocationDetailPanel'
export { AliasChip } from './AliasChip'
export type { AliasChipProps } from './AliasChip'
export { NewLocationInput } from './NewLocationInput'
export type { NewLocationInputProps } from './NewLocationInput'
export { LocationMergeDialog } from './LocationMergeDialog'
export type { LocationMergeDialogProps } from './LocationMergeDialog'

// ─── Extracted inline components ─────────────────────────────────────────────
export { DashboardCard } from './DashboardCard'
export { DashboardStatCard } from './DashboardStatCard'
export type { DashboardStatCardProps } from './DashboardStatCard'
export { MatchProgressBar } from './MatchProgressBar'
export type { MatchProgressBarProps } from './MatchProgressBar'
export { TripBarChart } from './TripBarChart'
export type { TripBarChartBar, TripBarChartProps } from './TripBarChart'
export { SortableTableHeader } from './SortableTableHeader'
export type { SortableTableHeaderProps, SortDirection } from './SortableTableHeader'
export { ActivityFeedItem } from './ActivityFeedItem'
export type { ActivityFeedItemProps } from './ActivityFeedItem'
export { MiniStatCard } from './MiniStatCard'
export type { MiniStatCardProps } from './MiniStatCard'
export { InfoBanner } from './InfoBanner'
export type { InfoBannerProps } from './InfoBanner'

// ─── Table primitives ────────────────────────────────────────────────────────
export { NepoTable } from './NepoTable'
export type { NepoColumn, NepoFooterCell, NepoTableProps } from './NepoTable'

// ─── Decoration & reveal ────────────────────────────────────────────────────────
export { CargoConstellationsCanvas } from './CargoConstellationsCanvas'
export type { CargoConstellationsCanvasProps } from './CargoConstellationsCanvas'
export { Reveal, RevealList } from './Reveal'
export { Decoration, HeroDecoration, SectionRouteDecoration, LiveDot } from './Decoration'
export { AnimatedNumber } from './AnimatedNumber'
export { PageTransition } from './PageTransition'

export { AddVehicleDialog } from './AddVehicleDialog'
export type { AddVehicleDialogProps } from './AddVehicleDialog'
export { AssignDriverDialog } from './AssignDriverDialog'
export type { AssignDriverDialogProps } from './AssignDriverDialog'
export { ResetPasswordDialog } from './ResetPasswordDialog'
export type { ResetPasswordDialogProps } from './ResetPasswordDialog'
export { DriverEditRow } from './DriverEditRow'
export type { DriverEditRowProps } from './DriverEditRow'
export { DriverRow } from './DriverRow'
export type { DriverRowProps } from './DriverRow'
export { DriverMobileCard, DriverMobileEditCard } from './DriverMobileCards'
export type { DriverMobileCardProps, DriverMobileEditCardProps } from './DriverMobileCards'


