"""initial schema

Revision ID: 001
Revises:
Create Date: 2026-05-05

Forward-only consolidated initial schema. Replaces the previous 25 staged
migrations after the BizLogic.md §10 22-column drop. Downgrade is a no-op
on purpose: this migration represents the post-overhaul ground state.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '001'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('tax_code', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('outstanding_debt', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_code'), 'clients', ['code'], unique=True)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_name'), 'clients', ['name'], unique=False)
    op.create_table('salary_period_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_day', sa.Integer(), nullable=False),
    sa.Column('to_day', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_period_configs_id'), 'salary_period_configs', ['id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('cccd', sa.String(length=12), nullable=True),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('tractor_plate', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_cccd'), 'users', ['cccd'], unique=True)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_vendor'), 'users', ['vendor'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('tax_code', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('contact_person', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendors_id'), 'vendors', ['id'], unique=False)
    op.create_index(op.f('ix_vendors_name'), 'vendors', ['name'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_table_name'), 'audit_logs', ['table_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('customer_import_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('template_name', sa.String(length=255), nullable=False),
    sa.Column('structure_hash', sa.String(length=64), nullable=False),
    sa.Column('sheet_name', sa.String(length=255), nullable=False),
    sa.Column('header_row_index', sa.Integer(), nullable=False),
    sa.Column('column_mapping', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('llm_cache', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_used_by', sa.Integer(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['last_used_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'structure_hash', name='uq_import_templates_client_structure')
    )
    op.create_index(op.f('ix_customer_import_templates_client_id'), 'customer_import_templates', ['client_id'], unique=False)
    op.create_index(op.f('ix_customer_import_templates_id'), 'customer_import_templates', ['id'], unique=False)
    op.create_index(op.f('ix_customer_import_templates_structure_hash'), 'customer_import_templates', ['structure_hash'], unique=False)
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('geocoded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('geocode_source', sa.String(length=20), nullable=True),
    sa.Column('pending_geocode', sa.Boolean(), nullable=False),
    sa.Column('created_via', sa.String(length=30), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('location_review_needed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_locations_id'), 'locations', ['id'], unique=False)
    op.create_index(op.f('ix_locations_name'), 'locations', ['name'], unique=True)
    op.create_table('salary_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('work_order_count', sa.Integer(), nullable=False),
    sa.Column('price_per_order', sa.Integer(), nullable=False),
    sa.Column('total_salary', sa.Integer(), nullable=False),
    sa.Column('total_allowance', sa.Integer(), nullable=False),
    sa.Column('total_deduction', sa.Integer(), nullable=False),
    sa.Column('net_pay', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_salary_periods_driver_id'), 'salary_periods', ['driver_id'], unique=False)
    op.create_index(op.f('ix_salary_periods_id'), 'salary_periods', ['id'], unique=False)
    op.create_table('location_aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('alias_normalized', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('alias_normalized')
    )
    op.create_index(op.f('ix_location_aliases_id'), 'location_aliases', ['id'], unique=False)
    op.create_index(op.f('ix_location_aliases_location_id'), 'location_aliases', ['location_id'], unique=False)
    op.create_index(op.f('ix_location_aliases_source'), 'location_aliases', ['source'], unique=False)
    op.create_table('pricings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('work_type', sa.String(length=10), nullable=False),
    sa.Column('pickup_location_id', sa.Integer(), nullable=False),
    sa.Column('dropoff_location_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['dropoff_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['pickup_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_id', 'work_type', 'pickup_location_id', 'dropoff_location_id', name='uq_pricings_lane')
    )
    op.create_index(op.f('ix_pricings_client_id'), 'pricings', ['client_id'], unique=False)
    op.create_index(op.f('ix_pricings_dropoff_location_id'), 'pricings', ['dropoff_location_id'], unique=False)
    op.create_index(op.f('ix_pricings_id'), 'pricings', ['id'], unique=False)
    op.create_index(op.f('ix_pricings_pickup_location_id'), 'pricings', ['pickup_location_id'], unique=False)
    op.create_table('routes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route', sa.String(length=500), nullable=False),
    sa.Column('pickup_location_id', sa.Integer(), nullable=False),
    sa.Column('dropoff_location_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['dropoff_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['pickup_location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pickup_location_id', 'dropoff_location_id', name='uq_routes_lane')
    )
    op.create_index(op.f('ix_routes_dropoff_location_id'), 'routes', ['dropoff_location_id'], unique=False)
    op.create_index(op.f('ix_routes_id'), 'routes', ['id'], unique=False)
    op.create_index(op.f('ix_routes_pickup_location_id'), 'routes', ['pickup_location_id'], unique=False)
    op.create_table('pricing_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pricing_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('driver_salary', sa.Integer(), nullable=False),
    sa.Column('allowance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pricing_id'], ['pricings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_lines_id'), 'pricing_lines', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_lines_pricing_id'), 'pricing_lines', ['pricing_id'], unique=False)
    op.create_table('trip_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_date', sa.Date(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('route', sa.String(length=500), nullable=False),
    sa.Column('pickup_location_id', sa.Integer(), nullable=False),
    sa.Column('dropoff_location_id', sa.Integer(), nullable=False),
    sa.Column('pricing_id', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('driver_salary', sa.Integer(), nullable=False),
    sa.Column('allowance', sa.Integer(), nullable=False),
    sa.Column('revenue', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_confirmed', sa.Boolean(), nullable=False),
    sa.Column('confirmed_by', sa.Integer(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.Integer(), nullable=True),
    sa.Column('pickup_raw', sa.String(length=500), nullable=True),
    sa.Column('dropoff_raw', sa.String(length=500), nullable=True),
    sa.Column('location_review_needed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['confirmed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dropoff_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pickup_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['pricing_id'], ['pricings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_orders_client_id'), 'trip_orders', ['client_id'], unique=False)
    op.create_index('ix_trip_orders_client_id_trip_date', 'trip_orders', ['client_id', 'trip_date'], unique=False)
    op.create_index(op.f('ix_trip_orders_code'), 'trip_orders', ['code'], unique=True)
    op.create_index('ix_trip_orders_confirmed_by', 'trip_orders', ['confirmed_by'], unique=False)
    op.create_index(op.f('ix_trip_orders_dropoff_location_id'), 'trip_orders', ['dropoff_location_id'], unique=False)
    op.create_index(op.f('ix_trip_orders_id'), 'trip_orders', ['id'], unique=False)
    op.create_index('ix_trip_orders_is_confirmed', 'trip_orders', ['is_confirmed'], unique=False)
    op.create_index(op.f('ix_trip_orders_pickup_location_id'), 'trip_orders', ['pickup_location_id'], unique=False)
    op.create_index('ix_trip_orders_status', 'trip_orders', ['status'], unique=False)
    op.create_index('ix_trip_orders_trip_date', 'trip_orders', ['trip_date'], unique=False)
    op.create_table('work_orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('route', sa.String(length=500), nullable=False),
    sa.Column('pickup_location_id', sa.Integer(), nullable=False),
    sa.Column('dropoff_location_id', sa.Integer(), nullable=False),
    sa.Column('driver_id', sa.Integer(), nullable=False),
    sa.Column('tractor_plate', sa.String(length=20), nullable=False),
    sa.Column('gps_lat', sa.Float(), nullable=True),
    sa.Column('gps_lng', sa.Float(), nullable=True),
    sa.Column('gps_address', sa.String(length=500), nullable=True),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('driver_salary', sa.Integer(), nullable=False),
    sa.Column('allowance', sa.Integer(), nullable=False),
    sa.Column('earning', sa.Integer(), nullable=False),
    sa.Column('pricing_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_locked', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['driver_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dropoff_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pickup_location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['pricing_id'], ['pricings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_orders_client_id'), 'work_orders', ['client_id'], unique=False)
    op.create_index(op.f('ix_work_orders_code'), 'work_orders', ['code'], unique=True)
    op.create_index('ix_work_orders_created_at', 'work_orders', ['created_at'], unique=False)
    op.create_index(op.f('ix_work_orders_driver_id'), 'work_orders', ['driver_id'], unique=False)
    op.create_index('ix_work_orders_driver_id_status', 'work_orders', ['driver_id', 'status'], unique=False)
    op.create_index(op.f('ix_work_orders_dropoff_location_id'), 'work_orders', ['dropoff_location_id'], unique=False)
    op.create_index(op.f('ix_work_orders_id'), 'work_orders', ['id'], unique=False)
    op.create_index(op.f('ix_work_orders_pickup_location_id'), 'work_orders', ['pickup_location_id'], unique=False)
    op.create_index('ix_work_orders_status', 'work_orders', ['status'], unique=False)
    op.create_table('trip_order_containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_order_id', sa.Integer(), nullable=False),
    sa.Column('container_number', sa.String(length=50), nullable=False),
    sa.Column('work_type', sa.String(length=10), nullable=False),
    sa.Column('container_size', sa.String(length=10), nullable=True),
    sa.Column('container_type', sa.String(length=20), nullable=True),
    sa.Column('freight_kind', sa.String(length=2), nullable=True),
    sa.Column('gross_weight_kg', sa.Float(), nullable=True),
    sa.Column('seal_no', sa.String(length=80), nullable=True),
    sa.Column('commodity', sa.String(length=500), nullable=True),
    sa.Column('container_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['trip_order_id'], ['trip_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_order_containers_container_number'), 'trip_order_containers', ['container_number'], unique=False)
    op.create_index(op.f('ix_trip_order_containers_id'), 'trip_order_containers', ['id'], unique=False)
    op.create_index(op.f('ix_trip_order_containers_trip_order_id'), 'trip_order_containers', ['trip_order_id'], unique=False)
    op.create_table('trip_order_work_orders',
    sa.Column('trip_order_id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trip_order_id'], ['trip_orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trip_order_id', 'work_order_id')
    )
    op.create_table('work_order_containers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_order_id', sa.Integer(), nullable=False),
    sa.Column('container_number', sa.String(length=50), nullable=False),
    sa.Column('work_type', sa.String(length=10), nullable=False),
    sa.Column('photo_url', sa.String(length=1000), nullable=True),
    sa.Column('photo_lat', sa.Float(), nullable=True),
    sa.Column('photo_lng', sa.Float(), nullable=True),
    sa.Column('photo_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('photo_address', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['work_order_id'], ['work_orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_order_containers_container_number'), 'work_order_containers', ['container_number'], unique=False)
    op.create_index(op.f('ix_work_order_containers_id'), 'work_order_containers', ['id'], unique=False)
    op.create_index(op.f('ix_work_order_containers_work_order_id'), 'work_order_containers', ['work_order_id'], unique=False)
    op.create_table('trip_container_photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trip_container_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('file_url', sa.String(length=1000), nullable=False),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('uploaded_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['trip_container_id'], ['trip_order_containers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trip_container_photos_id'), 'trip_container_photos', ['id'], unique=False)
    op.create_index(op.f('ix_trip_container_photos_kind'), 'trip_container_photos', ['kind'], unique=False)
    op.create_index(op.f('ix_trip_container_photos_trip_container_id'), 'trip_container_photos', ['trip_container_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    raise NotImplementedError(
        "This migration is forward-only. To rebuild from scratch, drop the "
        "database and re-run upgrade head."
    )
