"""add operation_types table

Revision ID: 487b1eccc88b
Revises: 0006_add_cont_photo_url
Create Date: 2026-06-03 15:46:55.476743

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "487b1eccc88b"
down_revision: Union[str, None] = "0006_add_cont_photo_url"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "operation_types",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("label", sa.String(length=50), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index(
        op.f("ix_operation_types_id"), "operation_types", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_driver_salaries_id"), "driver_salaries", ["id"], unique=False
    )

    # Seed existing operation types
    op.bulk_insert(
        sa.table(
            "operation_types",
            sa.column("id", sa.Integer),
            sa.column("name", sa.String),
            sa.column("label", sa.String),
            sa.column("is_active", sa.Boolean),
        ),
        [
            {
                "id": 1,
                "name": "XUẤT/NHẬP TÀU",
                "label": "Xuất / Nhập tàu",
                "is_active": True,
            },
            {"id": 2, "name": "CHUYỂN BÃI", "label": "Chuyển bãi", "is_active": True},
            {"id": 3, "name": "ĐÓNG KHO", "label": "Đóng kho", "is_active": True},
            {
                "id": 4,
                "name": "LẤY VỎ HẠ HÀNG",
                "label": "Lấy vỏ hạ hàng",
                "is_active": True,
            },
            {"id": 5, "name": "CHẠY SÀ LAN", "label": "Chạy sà lan", "is_active": True},
        ],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_driver_salaries_id"), table_name="driver_salaries")
    op.drop_index(op.f("ix_operation_types_id"), table_name="operation_types")
    op.drop_table("operation_types")
    # ### end Alembic commands ###
