"""add vendor type column

Revision ID: 5240104be019
Revises: 0011_add_mapping_profiles
Create Date: 2026-06-16 20:37:24.140031

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "5240104be019"
down_revision: Union[str, None] = "0011_add_mapping_profiles"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vendors",
        sa.Column(
            "type", sa.String(length=20), server_default="individual", nullable=False
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vendors", "type")
    # ### end Alembic commands ###
