"""allow_null_pickup_dropoff_on_booked_trips

Revision ID: 9633740b4b60
Revises: 487b1eccc88b
Create Date: 2026-06-03 19:17:05.147578

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9633740b4b60"
down_revision: Union[str, None] = "487b1eccc88b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "booked_trips", "pickup_location_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column(
        "booked_trips", "dropoff_location_id", existing_type=sa.INTEGER(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "booked_trips",
        "dropoff_location_id",
        existing_type=sa.INTEGER(),
        nullable=False,
    )
    op.alter_column(
        "booked_trips", "pickup_location_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
